# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-02 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='订单状态（1待支付，2待发货、3待签收'),
        ),
    ]
