# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='用户自身')),
                ('sid', models.IntegerField(verbose_name='被滑的陌生人')),
                ('mark', models.CharField(choices=[('like', '喜欢'), ('dislike', '不喜欢'), ('superlike', '超级喜欢')], max_length=20, verbose_name='滑动类型')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='滑动的时间')),
            ],
            options={
                'db_table': 'sp_swiped',
            },
        ),
    ]
