# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='uid1')),
                ('uid2', models.IntegerField(verbose_name='uid2')),
            ],
            options={
                'db_table': 'sp_friend',
            },
        ),
    ]
