# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-30 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='权限名称')),
                ('description', models.CharField(max_length=30, verbose_name='权限说明')),
            ],
            options={
                'db_table': 'db_permission',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('price', models.FloatField(verbose_name='价格')),
            ],
            options={
                'db_table': 'sp_vip',
            },
        ),
        migrations.CreateModel(
            name='VipPermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.IntegerField(verbose_name='vipid')),
                ('perm_id', models.IntegerField(verbose_name='权限id')),
            ],
            options={
                'db_table': 'sp_vip_perm_relation',
            },
        ),
    ]
