# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.CharField(choices=[('0', 'male'), ('1', 'female')], default='0', max_length=8, verbose_name='匹配的性别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_dating_age',
            field=models.IntegerField(default=50, verbose_name='最大交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.IntegerField(default=0, verbose_name='最大查找范围'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_dating_age',
            field=models.IntegerField(default=18, verbose_name='最小交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_distance',
            field=models.IntegerField(default=0, verbose_name='最小查找范围'),
        ),
    ]
