# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-02 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='礼物名称')),
                ('price', models.FloatField(default=0, verbose_name='礼物价格')),
                ('stock', models.IntegerField(default=0, verbose_name='礼物库存')),
                ('sales', models.IntegerField(default=0, verbose_name='礼物销量')),
            ],
            options={
                'db_table': 'sp_goods',
            },
        ),
    ]
